#!/usr/bin/env bash
# Project identity — the stable key that ties a repo to its memory database.
#
# WHY A FILE AND NOT THE FOLDER NAME: a project gets renamed, moved between machines (~/projects on
# Kali IS the Mac's home dir), and cloned. A path is not identity. This UUID is written once, is
# committed, and every row in that project's memory database carries it — so a row stays
# attributable even if the checkout moves or two projects are ever dumped together.
#
# THE COPY HAZARD THIS EXISTS TO SURVIVE: a new project is born as `cp -R ~/projects/_template
# ~/projects/<slug>`, which copies EVERY file — including this one. `make init` therefore calls
# `--regenerate`, not `--ensure`: without that, every scaffolded project would silently share the
# template's identity and collide in the registry. Two layers guard it, because a silent shared
# identity is unrecoverable once rows exist under it:
#   1. here — `make init` regenerates unconditionally;
#   2. at provision time — the registry rejects an id already held by a different repo, loudly.
# Neither layer alone is enough: (1) is skipped if someone copies without running init, and (2)
# only fires when a database is provisioned.
#
# Usage:
#   project-id.sh              print this project's id (exit 1 if there is none)
#   project-id.sh --ensure     create it if absent (idempotent), then print it
#   project-id.sh --regenerate replace it with a fresh id — for `make init` ONLY
#   project-id.sh --slug       print the recorded slug
# Optional 2nd arg to --ensure/--regenerate overrides the slug (default: directory basename).
set -euo pipefail

# ROOT is derived from THIS SCRIPT'S OWN LOCATION, deliberately — NOT from CLAUDE_PROJECT_DIR.
# The script always lives at <project>/scripts/project-id.sh, so its parent is always the right
# project. CLAUDE_PROJECT_DIR is the launch directory, which is $HOME whenever a session starts
# there (verified 2026-07-30) — trusting it would write .project-id into the home directory and
# stamp an unrelated identity. A wrong project root here is not a cosmetic bug: it is a wrong
# primary key on every memory row that follows.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FILE="$ROOT/.project-id"

# uuidgen is not universal (absent on some minimal images); the kernel and python fallbacks keep
# this working on any machine that opens the project. All three yield a v4 UUID.
gen_uuid() {
  if command -v uuidgen >/dev/null 2>&1; then uuidgen | tr 'A-Z' 'a-z'
  elif [ -r /proc/sys/kernel/random/uuid ]; then cat /proc/sys/kernel/random/uuid
  elif command -v python3 >/dev/null 2>&1; then python3 -c 'import uuid;print(uuid.uuid4())'
  else echo "project-id: no way to generate a UUID (need uuidgen, /proc, or python3)" >&2; return 1
  fi
}

# Slug rules mirror the folder convention AND Postgres identifier limits, because the slug becomes
# part of a database name (`memory_<slug>`) and a role name. Postgres truncates identifiers at 63
# bytes, so a slug that is too long would silently collide with another after truncation.
# `-` is not legal unquoted in an identifier, so it maps to `_` at the database layer, not here.
slugify() {
  printf '%s' "$1" | tr 'A-Z' 'a-z' | sed -E 's/[^a-z0-9_-]+/-/g; s/^-+//; s/-+$//' | cut -c1-40
}

read_field() { # $1=key — first match wins; tolerates comments and blank lines
  [ -f "$FILE" ] || return 1
  sed -n "s/^$1=//p" "$FILE" | head -1
}

write_file() { # $1=uuid $2=slug
  cat > "$FILE" <<EOF
# Project identity. GENERATED — do not hand-edit, and do not copy into another project.
# This id is the primary key for this project's memory database and is stamped on every row.
# Regenerated by \`make init\` when a new project is scaffolded from the template.
project_id=$1
slug=$2
created=$(date -u +%F)
EOF
}

mode="${1:-print}"
want_slug="${2:-}"

case "$mode" in
  print)
    id=$(read_field project_id 2>/dev/null || true)
    [ -n "${id:-}" ] || { echo "project-id: no .project-id in $ROOT (run: scripts/project-id.sh --ensure)" >&2; exit 1; }
    printf '%s\n' "$id" ;;
  --slug)
    s=$(read_field slug 2>/dev/null || true)
    [ -n "${s:-}" ] || { echo "project-id: no .project-id in $ROOT" >&2; exit 1; }
    printf '%s\n' "$s" ;;
  --ensure)
    if id=$(read_field project_id 2>/dev/null) && [ -n "$id" ]; then
      printf '%s\n' "$id"            # idempotent: an existing identity is NEVER silently replaced
    else
      s=$(slugify "${want_slug:-$(basename "$ROOT")}")
      id=$(gen_uuid); write_file "$id" "$s"
      echo "project-id: created $FILE (slug=$s)" >&2
      printf '%s\n' "$id"
    fi ;;
  --regenerate)
    s=$(slugify "${want_slug:-$(basename "$ROOT")}")
    old=$(read_field project_id 2>/dev/null || true)
    id=$(gen_uuid); write_file "$id" "$s"
    [ -n "${old:-}" ] && echo "project-id: replaced $old -> $id (slug=$s)" >&2 || echo "project-id: created $id (slug=$s)" >&2
    printf '%s\n' "$id" ;;
  *)
    echo "usage: project-id.sh [--ensure|--regenerate|--slug] [slug]" >&2; exit 2 ;;
esac
